using Chronozoom.Library.Repositories;
using ChronoZoom.Mongo.Models;
using MongoDB.Bson;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ChronoZoom.Mongo.PersistencyEngine
{
    public class UserFactory : IUserRepository
    {

        private const string COLLECTION_NAME = "User";

        private UserFactory() { }

        /// <summary>
        /// Finds a user by his unique identifier
        /// </summary>
        /// <param name="userId">The unique identifier of the user</param>
        /// <returns>The user object or null</returns>
        public static async Task<User> FindByIdAsync(ObjectId userId) 
        {
            var collection = MongoFactory.database.GetCollection<User>("user");
            var user = await collection.Find<User>(x => x.Id == userId).FirstOrDefaultAsync();

            return user;
        }

        /// <summary>
        /// Finds a user by his name
        /// </summary>
        /// <param name="name">The name of the user</param>
        /// <returns>The user object or null</returns>
        public static async Task<User> FindByNameAsync(String name) 
        {
            var collection = MongoFactory.database.GetCollection<User>("user");
            var user = await collection.Find<User>(x => x.Name == name).FirstOrDefaultAsync();

            return user;
        }

        /// <summary>
        /// Finds a user by his email
        /// </summary>
        /// <param name="email">The email of the user to be found</param>
        /// <returns>The user object or null</returns>
        public static async Task<User> FindByEmailAsync(String email)
        {
            var collection = MongoFactory.database.GetCollection<User>("user");
            var user = await collection.Find<User>(x => x.Email == email).FirstOrDefaultAsync();

            return user;
        }

        /// <summary>
        /// Creates a User in the database
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        public static async Task<Boolean> InsertAsync(User user) 
        {
            var collection = MongoFactory.database.GetCollection<User>("user");
            await collection.InsertOneAsync(user);

            return true;
        }


        /// <summary>
        /// Updates a user in the database.
        /// For now, we update the entire user object. This is not ideal and definitely not the neatest way
        /// to do this. But it's fast and it's effective.
        /// </summary>
        /// <param name="user">The updated user object</param>
        /// <returns>ReplaceOneResult generated by the MongoDB server</returns>
        public static async Task<ReplaceOneResult> UpdateAsync(User user) 
        {
            var collection = MongoFactory.database.GetCollection<User>(COLLECTION_NAME);
            var updateResult = await collection.ReplaceOneAsync<User>(x => x.Id.Equals(user.Id), user, new UpdateOptions { IsUpsert = true});

            return updateResult;
        }

        /// <summary>
        /// Deletes a user from the database. Permanently.
        /// </summary>
        /// <param name="user"></param>
        /// <returns>DeleteResult generated by the MongoDB server</returns>
        public static async Task<DeleteResult> DeleteAsync(User user) 
        {
            var collection = MongoFactory.database.GetCollection<User>(COLLECTION_NAME);
            var deleteResult = await collection.DeleteOneAsync<User>(x => x.Id.Equals(user.Id));

            return deleteResult;
        }
    }
}
